version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db:
    driver: local
